BRANDS: dict[str:str] = {
    "AMTEL": "Amtel",
    "AOTELI": "Aoteli",
    "APLUS": "Aplus",
    "ARIVO": "Arivo",
    "ATTAR": "Attar",
    "O'GREEN": "O'Green",
    "BARS": "Bars",
    "BF GOODRICH": "BF Goodrich",
    "BRIDGESTONE": "Bridgestone",
    "CENTARA": "Centara",
    "CONTINENTAL": "Continental",
    "CORDIANT": "Cordiant",
    "CROSSLEADER": "Crossleader",
    "DOUBLESTAR": "DoubleStar",
    "DUNLOP": "Dunlop",
    "DYNAMO": "Dynamo",
    "FALKEN": "Falken",
    "FORMULA": "Formula",
    "FIREMAX": "Firemax",
    "GENERAL TIRE": "General Tire",
    "GISLAVED": "Gislaved",
    "GOODYEAR": "GoodYear",
    "GOOD YEAR": "GoodYear",
    "HANKOOK": "Hankook",
    "HIFLY": "HiFly",
    "HI-FLY": "HiFly",
    "IKON TYRES": "Ikon",
    "IKON": "Ikon",
    "NORDMAN": "Ikon",
    "КАМА": "КАМА",
    "KAMA": "КАМА",
    "KAPSEN": "Kapsen",
    "KUMHO": "Kumho",
    "LANVIGATOR": "Lanvigator",
    "LAUFENN": "Laufenn",
    "LEAO": "Leao",
    "LINGLONG": "Linglong",
    "LING LONG": "Linglong",
    "MASSIMO": "Massimo",
    "MAXXIS": "MAXXIS",
    "MAZZINI": "Mazzini",
    "MICHELIN": "Michelin",
    "NEXEN": "Nexen",
    "NITTO": "Nitto",
    "NOKIAN TYRES": "Nokian",
    "NOKIAN": "Nokian",
    "ONYX": "Onyx",
    "PACE": "Pace",
    "PIRELLI": "Pirelli",
    "POWERTRAC": "Powertrac",
    "ROADCRUZA": "Roadcruza",
    "ROADMARCH": "Roadmarch",
    "ROTALLA": "Rotalla",
    "ROYAL BLACK": "Royal Black",
    "SAILUN": "Sailun",
    "SONIX": "Sonix",
    "SUMAXX": "Sumaxx",
    "TIGAR": "Tigar",
    "TORERO (MATADOR)": "Torero (Matador)",
    "TORERO": "Torero",
    "TOYO": "Toyo",
    "MATADOR": "Matador",  # Должен быть после Torero
    "TRIANGLE": "Triangle",
    "TUNGA": "Tunga",
    "VIATTI": "Viatti",
    "VOLTYRE": "Voltyre",
    "WESTLAKE": "Westlake",
    "WIDEWAY": "Wideway",
    "WINRUN": "Winrun",
    "YOKOHAMA": "Yokohama",
    "NKSHZ": "КАМА",
    "НКШЗ": "КАМА",
    "БЕЛШИНА": "БелШина",
    "ВОЛШЗ": "ВолШЗ",
}

MODELS: dict[str:str] = {
    "Amtel": {
        "NORDMASTER CL": "NordMaster CL",
    },
    "Aoteli": {
        "ECOSAVER": "Ecosaver",
    },
    "Aplus": {
        "A503": "A503",
        "A703": "A703",
    },
    "Arivo": {
        "ICE CLAW ARW7": "Ice Claw ARW7",
        "ICE CLAW ARW8": "Ice Claw ARW8",
    },
    "Attar": {
        "S01": "S01",
        "S02": "S02",
        "S03": "S03",
        "W03": "W03",
    },
    "Bars": {
        "SOLARFLEXX": "SolarFlexx",
        "UZ100": "UZ100",
        "UZ200": "UZ200",
        "UZ300": "UZ300",
    },
    "BF Goodrich": {
        "G-FORCE COMP-2": "G-Force Comp-2",
        "MUD TERRAIN T/A KM3": "Mud Terrain T/A KM3",
        "WINTER T/A KSI ": "Winter T/A KSI",
    },
    "Bridgestone": {
        "ALENZA 001": "Alenza 001",
        "BLIZZAK DM-V2": "Blizzak DM-V2",
        "BLIZZAK DM-V3": "Blizzak DM-V3",
        "BLIZZAK ICE": "Blizzak Ice",
        "BLIZZAK SPIKE-01": "Blizzak Spike-01",
        "SPIKE-01": "Blizzak Spike-01",
        "BLIZZAK SPIKE-02": "Blizzak Spike-02",
        "SPIKE-02": "Blizzak Spike-02",
        "BLIZZAK VRX": "Blizzak VRX",
        "DM-V2": "DM-V2",
        "DMV-2": "DM-V2",
        "DUELER A/T 001": "Dueler A/T 001",
        "DUELER M/T 674": "Dueler M/T 674",
        "ECOPIA EP300": "Ecopia EP300",
        "IC7000": "IC7000",
        "REVO-GZ": "Revo GZ",
        "REVO GZ": "Revo GZ",
        "R250": "R250",
        "TURANZA T005A": "Turanza T005A",
        "TURANZA T005": "Turanza T005",
    },
    "Centara": {
        "COMMERCIAL": "Commercial",
    },
    "Continental": {
        "CONTIECO": "Contieco",
        "CONTIVANCONTACT 100": "ContiVanContact 100",
        "ECOCONTACT 6": "EcoContact 6",
        "ICECONTACT 2": "IceContact 2",
        "ICE CONTACT 2": "IceContact 2",
        "ICECONTACT 3": "IceContact 3",
        "ICE CONTACT 3": "IceContact 3",
        "PREMIUM CONTACT 6": "Premium Contact 6",
        "VIKINGCONTACT 7": "VikingContact 7",
        "VIKING CONTACT 7": "VikingContact 7",
    },
    "Cordiant": {
        "ALL TERRAIN": "All-Terrain",
        "ALL-TERRAIN": "All-Terrain",
        "CA-1": "Business CA-1",
        "CA-2": "Business CA-2",
        "CS-2": "Business CS-2",
        "CW-2": "Business CW-2",
        "BUSINESS CW-2": "Business CW-2",
        "COMFORT 2": "Comfort 2",
        "COMFORT-2": "Comfort 2",
        "GRAVITY": "Gravity",
        "OFF ROAD OS-501": "Off Road OS-501",
        "OFF ROAD 2": "Off-Road 2",
        "OFF ROAD  2": "Off-Road 2",
        "PW-404": "Polar SL PW-404",
        "POLAR SL": "Polar SL PW-404",
        "PW-502": "Polar 2 PW-502",
        "POLAR-2": "Polar 2 PW-502",
        "ROAD RUNNER PS-1": "Road Runner PS-1",
        "ROAD RUNNER": "Road Runner PS-1",
        "RUN TOUR": "RUN TOUR",
        "PW-2": "Snow Cross PW-2",
        "PW-4": "Snow Cross 2 PW-4",
        "SNOW CROSS 2": "Snow Cross 2 PW-4",
        "SNOW-CROSS 2": "Snow Cross 2 PW-4",
        "SNOW- CROSS 2": "Snow Cross 2 PW-4",
        "SNOW CROSS": "Snow Cross PW-2",
        "SNO-MAX 7000": "Sno-Max 7000",
        "PS-2": "Sport 3 PS-2",
        "SPORT 3": "Sport 3 PS-2",
        "SPORT-3": "Sport 3 PS-2",
        "WINTER DRIVE 2": "Winter Drive 2",
        "PW-1": "Winter Drive PW-1",
        "WINTER DRIVE": "Winter Drive PW-1",
        "WINTER-DRIVE": "Winter Drive PW-1",
    },
    "Crossleader": {
        "DH08": "DH08",
    },
    "DoubleStar": {
        "DH01": "DH01",
        "DH02": "DH02",
        "DH05": "DH05",
        "DS01": "DS01",
        "DW02": "DW02",
    },
    "Dynamo": {
        "MAT01": "Hiscend-H MAT01",
        "MC01": "Hiscend-H MC01",
        "MC02": "Hiscend-H MC02",
        "MHT01": "Hiscend-H MHT01",
        "MMT01": "Hiscend-H MMT01",
        "MSU01": "Hiscend-H MSU01",
        "MSU02": "Hiscend-H MSU02",
        "SNOW-H ARCTIC EVO": "Snow-H Arctic Evo",
        "SNOW-H ARCTIC": "Snow-H Arctic",
        "SNOW-H MSL01": "Snow-H MSL01",
        "MWCS01": "Snow-H MWCS01",
        "MWC01": "Snow-H MWC01",
        "MWH01": "Snow-H MWH01",
        "MWH02": "Snow-H MWH02",
        "MWH03": "Snow-H MWH03",
        "MWS01": "Snow-H MWS01",
        "MH01": "Street-H MH01",
        "MU02": "Street-H MU02",
        "MU71": "Street-H MU71",
    },
    "Dunlop": {
        "GRANDTREK AT5": "Grandtrek AT5",
        "GRANDTREK ICE02": "Grandtrek Ice 02",
        "GRANDTREK ICE 02": "Grandtrek Ice 02",
        "GRANDTREK ICE03": "Grandtrek Ice 03",
        "GRASPIC DS3": "Graspic DS3",
        "SP SPORT LM705W": "SP Sport LM705W",
        "SP WINTER ICE 02": "SP Winter Ice 02",
        "SP WINTER ICE02": "SP Winter Ice 02",
        "SP WINTER ICE 03": "SP Winter Ice 03",
        "SP WINTER ICE03": "SP Winter Ice 03",
        "WINTER MAXX SJ8": "Winter MAXX SJ8",
        "WINTER MAXX WM01": "Winter MAXX WM01",
        "WINTER MAXX WM02": "Winter MAXX WM02",
    },
    "Falken": {
        "AZENIS FK510A": "Azenis FK510A",
    },
    "Firemax": {
        "FM601": "FM601",
        "FM810": "FM810",
    },
    "Formula": {
        "ENERGY": "Energy",
        "ICE FRICTION": "Ice FR",
        "ICE FR": "Ice FR",
        "ICE": "Ice",
    },
    "General Tire": {
        "ALTIMAX ARCTIC 12 CD": "Altimax Arctic 12 CD",
    },
    "Gislaved": {
        "ACTIVECONTROL": "ActiveControl",
        "ARCTICCONTROL": "ArcticControl",
        "ECOCONTROL": "EcoControl",
        "ICECONTROL": "IceControl",
        "ICE CONTROL": "IceControl",
        "NORD FROST 200 HD": "Nord Frost 200 HD",
        "NORD FROST 200 ID": "Nord Frost 200 ID",
        "NORD FROST 200": "Nord Frost 200",
        "NORD*FROST 200": "Nord Frost 200",
        "NORD FROST VAN SD": "Nord Frost VAN SD",
        "NORD FROST VAN 2": "Nord Frost VAN 2",
        "PREMIUMCONTROL": "PremiumControl",
        "PREMIUM CONTROL": "PremiumControl",
        "SOFT FROST 200": "Soft Frost 200",
        "SOFT*FROST 200": "Soft Frost 200",
        "SPIKECONTROL": "SpikeControl",
        "SPIKE CONTROL": "SpikeControl",
        "TERRACONTROL ATR": "TerraControl ATR",
        "TERRA CONTROL ATR": "TerraControl ATR",
        "TERRACONTROL": "TerraControl",
        "TERRA CONTROL": "TerraControl",
        "ULTRACONTROL": "UltraControl",
        "ULTRA CONTROL": "UltraControl",
    },
    "GoodYear": {
        "EAGLE F1 ASYMMETRIC 5": "Eagle F1 Asymmetric 5",
        "EAGLE SPORT TZ": "Eagle Sport TZ",
        "ULTRA GRIP ARCTIC 2": "Ultra Grip Arctic 2",
        "ULTRA GRIP ICE ARCTIC": "Ultra Grip Ice Arctic",
        "ULTRAGRIP ICE ARCTIC": "Ultra Grip Ice Arctic",
        "ULTRA GRIP ICE 2": "Ultra Grip Ice 2",
        "ULTRAGRIP ICE SUV GEN-1": "Ultra Grip Ice GEN-1",
    },
    "Hankook": {
        "H750": "Kinergy 4S2 H750",
        "IW01A": "IW01A",
        "IW04A": "iON Nordic i*ce IW04A",
        "RF11": "Dynapro AT2 RF11",
        "RA33": "Dynapro HP2 RA33",
        "RA43": "Dynapro HPX RA43",
        "RT03": "RT03",
        "RT05": "RT05",
        "RW08": "RW08",
        "K125A": "Ventus Prime 3 K125A",
        "K125": "Ventus Prime 3 K125",
        "K127A": "Ventus S1 Evo3 K127A",
        "K127B": "Ventus S1 Evo3 K127B Run Flat",
        "K127": "Ventus S1 Evo3 K127",
        "K135": "Ventus Prime 4 K135",
        "K137": "Ventus Evo K137",
        "K435": "Kinergy Eco2 K435",
        "K715": "K715",
        "RA30": "RA30",
        "RW06": "RW06",
        "RW10": "Winter I*Cept X RW10",
        "RW11": "I*Pike RW11",
        "RW15": "RW15",
        "W330": "Winter I*Cept Evo3 W330",
        "W330A": "Winter I*Cept Evo3 X W330A",
        "W429A": "Winter I*Pike X W429A",
        "W429": "Winter I*Pike RS2 W429",
        "W616": "W616",
        "W636": "Winter I*Cept IZ3 W636",
        "W636A": "Winter I*Cept IZ3 X W636A",
    },
    "HiFly": {
        "HF-261": "HF-261",
    },
    "Ikon": {
        "AUTOGRAPH AQUA 3": "Autograph Aqua 3",
        "AUTOGRAPH ECO C3": "Autograph Eco C3",
        "AUTOGRAPH ECO 3": "Autograph Eco 3",
        "AUTOGRAPH ICE C3": "Autograph Ice C3",
        "AUTOGRAPH ICE LT3": "Autograph Ice LT3",
        "AUTOGRAPH ICE 9": "Autograph Ice 9",
        "AUTOGRAPH ICE 10": "Autograph Ice 10",
        "AUTOGRAPH SNOW C3": "Autograph Snow C3",
        "AUTOGRAPH SNOW 3": "Autograph Snow 3",
        "AUTOGRAPH SNOW 5": "Autograph Snow 5",
        "AUTOGRAPH ULTRA 2": "Autograph Ultra 2",
        "CHARACTER AQUA": "Character Aqua",
        "CHARACTER ECO": "Character Eco",
        "CHARACTER ICE 7 SUV (NORDMAN 7 SUV)": "Character Ice 7 SUV (Nordman 7 SUV)",
        "CHARACTER ICE 7 (NORDMAN 7)": "Character Ice 7 (Nordman 7)",
        "CHARACTER ICE 7": "Character Ice 7",
        "CHARACTER ICE 8 SUV (NORDMAN 8 SUV)": "Character Ice 8 SUV (Nordman 8 SUV)",
        "CHARACTER ICE 8 (NORDMAN 8)": "Character Ice 8 (Nordman 8)",
        "CHARACTER ICE 8": "Character Ice 8",
        "CHARACTER SNOW 2 SUV (NORDMAN RS2 SUV)": "Character Snow 2 SUV (Nordman RS2 SUV)",
        "CHARACTER SNOW 2 (NORDMAN RS2)": "Character Snow 2 (Nordman RS2)",
        "CHARACTER SNOW 2": "Character Snow 2",
        "CHARACTER ULTRA": "Character Ultra",
        "NORDMAN C": "Nordman C",
        "NORDMAN RS2": "Nordman RS2",
        "RS2": "Nordman RS2",
        "NORDMAN SC": "Nordman SC",
        "SC": "Nordman SC",
        "NORDMAN SX3": "Nordman SX3",
        "SX3": "Nordman SX3",
        "NORDMAN SZ2": "Nordman SZ2",
        "SZ2": "Nordman SZ2",
        "NORDMAN S2": "Nordman S2",
        "S2": "Nordman S2",
        "NORDMAN 5": "Nordman 5",
        "NORDMAN 7": "Nordman 7",
        "NORDMAN 8": "Nordman 8",
    },
    "КАМА": {
        "531(ALGA)": "Alga 531",
        "ALGA": "Alga",
        "НК-132": "Breeze НК-132",
        "EURO 129": "Евро-129",
        "ЕВРО-131 LCV": "Евро-131 LCV",
        "ЕВРО-131": "Евро-131",
        "EURO 131": "Евро-131",
        "EURO-518": "Euro-518",
        "ЕВРО 518": "Euro-518",
        "EURO 519": "Euro-519",
        "EURO-520": "Euro НК-520",
        "ЕВРО-520": "Euro НК-520",
        "EURO 520": "Euro НК-520",
        "НК-520": "Euro НК-520",
        "LCV-131": "Euro LCV-131 НкШЗ",
        "НК-245": "Flame A/T НК-245 НкШЗ",
        "FLAME M/T LCV": "Flame M/T LCV",
        "FLAME M/T": "Flame M/T",
        "НК-434": "Flame М/T НК-434",
        "FLAME": "Flame",
        "241 GRANT": "241 Grant",
        "V-134": "Strada 2 V-134 НкШЗ",
        "НК-135": "Trace НК-135 НкШЗ",
        "TRACE(135)": "Trace НК-135 НкШЗ",
        "И-502": "И-502 НкШЗ M+S",
        "И-511": "И-511",
        "И-520": "И-520 НкШЗ",
        "КАМА-218": "Кама-218",
        "КАМА-219": "Кама-219 НкШЗ",
        "КАМА-221": "Кама-221",
        "КАМА-503": "Кама-503",
        "KAMA-503": "Кама-503",
        "365 HK-241": "365 HK-241 НкШЗ",
        "НК-241": "НК-241",
        "HK-241": "НК-241",
        "241": "241",
        "HK-242": "НК-242 НкШЗ",
        "242": "НК-242 НкШЗ",
        "132": "132",
        "244": "244",
        "503": "503",
        "НК-243": "НК-243 НкШЗ",
        "НК-534": "НК-534",
    },
    "Kapsen": {
        "S2000": "S2000",
    },
    "Kumho": {
        "AT52": "AT52",
        "CW11": "CW11",
        "ECSTA EV PS71": "Ecsta EV PS71",
        "ECSTA PS71": "Ecsta PS71",
        "HP71": "HP71",
        "HP91": "HP91",
        "HS51": "HS51",
        "HS52": "HS52",
        "MT51": "MT51",
        "MT71": "MT71",
        "KC11": "KC11",
        "KC53": "KC53",
        "KH27": "KH27",
        "KL71": "KL71",
        "PS31": "PS31",
        "PS71": "PS71",
        "PS72": "PS72",
        "RS02": "RS02",
        "WI31": "WI31",
        "WI32": "WI32",
        "WI51": "WI51",
        "WS31": "WS31",
        "WS51": "WS51",
    },
    "Lanvigator": {
        "WINTERGRIP VAN": "WinterGrip VAN",
        "S600": "S600",
    },
    "Laufenn": {
        "LC01": "LC01",
        "LD01": "LD01",
        "LH01": "LH01",
        "LH71": "LH71",
        "LK01": "LK01",
        "LK03": "LK03",
        "LK41": "LK41",
        "LV01": "LV01",
        "LW31": "LW31",
        "LW51": "LW51",
        "LW71": "LW71",
        "LY31": "LY31",
    },
    "Leao": {
        "WINTER DEFENDER ICE I-15": "Winter Defender Ice I-15",
    },
    "Linglong": {
        "COMFORT MASTER": "Comfort Master",
        "CROSSWIND A/T100": "Crosswind A/T 100",
        "CROSSWIND A/T": "Crosswind A/T",
        "CROSSWIND H/T": "Crosswind H/T",
        "CROSSWIND M/T": "Crosswind M/T",
        "CROSSWIND STORM 01 8PR M+S": "Crosswind Storm 01 8PR M+S",
        "CROSSWIND 4×4 HP": "Crosswind 4×4 HP",
        "CROSSWIND 4X4 HP": "Crosswind 4×4 HP",
        "GREEN MAX ECOTOURING": "Green-Max EcoTouring",
        "GREEN-MAX ECOTOURING": "Green-Max EcoTouring",
        "GREEN MAX HP010": "Green-Max HP010",
        "GREEN-MAX HP010": "Green-Max HP010",
        "GREEN MAX VAN": "Green-Max VAN",
        "GREEN-MAX VAN": "Green-Max VAN",
        "GREENMAX WINTER GRIP VAN 2": "Green-Max Winter Grip Van 2",
        "GREEN MAX WINTER GRIP VAN 2": "Green-Max Winter Grip Van 2",
        "GREEN-MAX WINTER GRIP 2": "Green-Max Winter Grip 2",
        "GREEN MAX WINTER GRIP": "Green-Max Winter Grip",
        "GREEN-MAX WINTER GRIP": "Green-Max Winter Grip",
        "GREEN-MAX WINTER ICE I-15": "Green-Max Winter Ice I-15",
        "GREEN MAX WINTER VAN": "Green-Max Winter Van",
        "GREEN-MAX WINTER VAN": "Green-Max Winter Van",
        "GREEN MAX 4×4 HP": "Green-Max 4×4 HP",
        "GREEN-MAX 4×4 HP": "Green-Max 4×4 HP",
        "GREEN MAX 4X4 HP": "Green-Max 4×4 HP",
        "GREEN-MAX 4X4 HP": "Green-Max 4×4 HP",
        "GREEN-MAX": "Green-Max",
        "GRIP MASTER C/S": "Grip Master C/S",
        "GRIP MASTER 4S": "Grip Master 4S",
        "R620": "R620",
        "NORD MASTER": "Nord Master",
        "SPORT MASTER E EV": "Sport Master E EV",
        "SPORT MASTER": "Sport Master",
    },
    "Massimo": {
        "VITTO": "Vitto",
    },
    "Matador": {
        "SIBIR ICE 2": "Sibir Ice 2 MP-30",
        "MP47 HECTORRA 3": "Hectorra 3 MP47",
        "MP-54 SIBIR SNOW": "Sibir Snow MP-54",
        "MP72": "Izzarda A/T 2 MP-72",
        "MP-92 SIBIR SNOW": "Sibir Snow MP-92",
        "MP-72": "Izzarda A/T 2 MP-72",
        "MPS-125 VARIANT AW": "Variant AW MPS-125",
        "MPS-330 MAXILLA 2": "Maxilla 2 MPS-330",
        "MPS-500 SIBIR ICE VAN SD": "Sibir Ice Van SD MPS-500",
        "MPS-530 SIBIR SNOW VAN": "Sibir Snow Van MPS-530",
    },
    "MAXXIS": {
        "AT 771": "Bravo A/T 771",
        "AT-771": "Bravo A/T 771",
        "AT 980E": "Worm-Drive A/T 980E",
        "AT-980E": "Worm-Drive A/T 980E",
        "AT 980": "Worm-Drive A/T 980",
        "AT-980": "Worm-Drive A/T 980",
        "MT 764": "Bighorn M/T 764",
        "MT-764": "Bighorn M/T 764",
        "MP10": "Pragmatra MP10",
        "MP15": "Pragmatra MP15",
        "HP5": "Premitra HP5",
        "MA-SLW": "MA-SLW",
        "MA-Z3": "MA-Z3",
        "MAZ4S": "Victra MA-Z4S",
        "MA Z4S": "Victra MA-Z4S",
        "MA-Z4S": "Victra MA-Z4S",
        "VS5": "Victra Sport VS5",
        "NP-5": "NP-5",
        "NS-5": "NS-5",
        "SP-02": "SP-02",
        "SP3": "SP3",
        "SP5": "SP5",
        "SS-01": "SS-01",
        "UE-168": "Bravo UE-168",
    },
    "Mazzini": {
        "ECO307": "ECO307",
        "ECO605 PLUS": "ECO605 Plus",
        "ECO606": "ECO606",
        "ECO607": "ECO607",
        "ECO809": "ECO809",
        "ECO819": "ECO819",
        "ECOSAVER": "Ecosaver",
        "EFFIVAN": "EffiVan",
        "FALCONER F1": "Falconer F1",
        "GIANTSAVER": "Giantsaver",
        "MUD CONTENDER": "Mud Contender",
        "SHARK A30": "Shark A30",
        "SHARK Z02": "Shark-Z02",
        "SHARK-Z02": "Shark-Z02",
        "SNOWLEOPARD": "Snow Leopard",
        "SNOW LEOPARD": "Snow Leopard",
        "VARENNA S01": "Varenna S01",
        "VARENNA SO1": "Varenna S01",
    },
    "Michelin": {
        "PILOT SPORT 4S": "Pilot Sport 4S",
        "PILOT SPORT 4": "Pilot Sport 4",
        "PRIMACY 4+": "Primacy 4+",
        "LAT. X-ICE NORTH": "Latitude X-ice North",
        "LATITUDE CROSS": "Latitude Cross",
        "LATITUDE TOUR HP": "Latitude Tour HP",
        "LATITUDE X-ICE 2": "Latitude X-ice 2",
        "XDE2": "XDE2",
        "X-ICE NORTH 4": "X-ice North 4",
        "X-ICE SNOW MI": "X-ice Snow MI",
        "X-ICE SNOW": "X-ice Snow",
    },
    "Nexen": {
        "CP321": "CP321",
        "N'BLUE HD PLUS": "N'Blue Hd Plus",
        "N’BLUE HD PLUS": "N'Blue Hd Plus",
        "NBLUE S": "N'Blue S",
        "N'FERA RU1": "N'Fera RU1",
        "N’FERA RU1": "N'Fera RU1",
        "N'FERA RU5": "N’Fera RU5",
        "N’FERA RU5": "N’Fera RU5",
        "N'FERA SPORT": "N’Fera Sport",
        "N’FERA SPORT": "N’Fera Sport",
        "N'FERA SU1": "N'Fera SU1",
        "N’FERA SU1": "N'Fera SU1",
        "ROADIAN A/T": "Roadian A/T",
        "ROADIAN HP": "Roadian HP",
        "ROADIAN HTX RH5": "Roadian HTX RH5",
        "ROADIAN HTX 2": "Roadian HTX 2",
        "WILDRANGER AT": "Wildranger A/T",
        "WILDRANGER A/T": "Wildranger A/T",
        "WINGUARD WINSPIKE": "Winguard Winspike",
        "WINGUARD": "Winguard",
    },
    "Nitto": {
        "NTSN3": "NTSN3",
        "NTSPK": "NTSPK",
        "DURA GRAPPLER": "Dura Grappler",
    },
    "Nokian": {
        "HAKKA GREEN 3": "Hakka Green 3",
        "HAKKAPELIITTA BLACK 2": "Hakkapeliitta Black 2",
        "HAKKAPELIITTA BLUE 3": "Hakkapeliitta Blue 3",
        "HAKKAPELIITTA C3": "Hakkapeliitta C3",
        "HAKKAPELIITTA CR3": "Hakkapeliitta CR3",
        "HAKKAPELIITTA GREEN 3": "Hakkapeliitta Green 3",
        "HAKKAPELIITTA LT3": "Hakkapeliitta LT3",
        "HAKKAPELIITTA R2": "Hakkapeliitta R2",
        "HAKKAPELIITTA R3": "Hakkapeliitta R3",
        "HAKKAPELIITTA R5": "Hakkapeliitta R5",
        "HAKKAPELIITTA R": "Hakkapeliitta R",
        "HAKKAPELIITTA VAN": "Hakkapeliitta VAN",
        "HAKKAPELIITTA 9": "Hakkapeliitta 9",
        "HAKKAPELIITTA 10P": "Hakkapeliitta 10p",
        "HAKKA BLUE 3": "Hakka Blue 3",
        "NORDMAN C": "Nordman C",
        "NORDMAN RS2": "Nordman RS2",
        "NORDMAN SC": "Nordman SC",
        "NORDMAN SX3": "Nordman SX3",
        "NORDMAN SZ2": "Nordman SZ2",
        "NORDMAN S2": "Nordman S2",
        "NORDMAN 5": "Nordman 5",
        "NORDMAN 7": "Nordman 7",
        "NORDMAN 8": "Nordman 8",
    },
    "Onyx": {
        "NY-W387": "NY-W387",
    },
    "O'Green": {
        "AG168 14PR": "AG168 14PR",
        "AG168": "AG168",
        "AG896 14PR": "AG896 14PR",
        "AG896": "AG896",
    },
    "Pace": {
        "ALVENTI RUN FLAT": "Alventi Run Flat",
        "ALVENTI": "Alventi",
        "ANTARCTICA ICE": "Antarctica Ice",
        "ANTARCTICA SPORT": "Antarctica Sport",
        "IMPERO": "Impero",
    },
    "Pirelli": {
        "FORMULA ENERGY": "Formula Energy",
        "ENERGY": "Formula Energy",
        "FORMULA ICE": "Formula Ice",
        "CINTURATO ALL SEASON 2": "Cinturato All Season 2",
        "CINTURATO P1": "Cinturato P1",
        "NEW CINTURATO P7": "NEW Cinturato P7",
        "CINTURATO P7  RUN FLAT": "Cinturato P7 Run Flat",
        "CINTURATO P7 RUN FLAT": "Cinturato P7 Run Flat",
        "CINTURATO P7 (P7C2)": "Cinturato P7 (P7C2)",
        "CINTURATO P7": "Cinturato P7",
        "CINTURATO WINTER": "Cinturato Winter",
        "CHRONO": "Chrono",
        "POWERGY": "Powergy",
        "P-ZERO LUXURY SALOON RUN FLAT": "P Zero Luxury Saloon Run Flat",
        "P ZERO RUN FLAT": "P Zero Run Flat",
        "P-ZERO (PZ4) LUXURY SALOON RUN FLAT": "P Zero (PZ4) Luxury Saloon Run Flat",
        "P-ZERO (PZ4) LUXURY SALOON": "P Zero (PZ4) Luxury Saloon",
        "P-ZERO (PZ4) SPORTS CAR PNCS": "P Zero (PZ4) Sports Car (PNCS)",
        "P-ZERO (PZ4) SPORTS CAR": "P Zero (PZ4) Sports Car",
        "P ZERO SPORTS CAR": "P Zero Sports Car",
        "P-ZERO SPORTS CAR": "P Zero Sports Car",
        "P ZERO WINTER": "P Zero Winter",
        "P ZERO": "P Zero",
        "ZERO PNCS": "Zero (PNCS)",
        "SCORPION ALL SEASON SF2": "Scorpion All-Season SF2",
        "SCORPION ALL-SEASON SF2": "Scorpion All-Season SF2",
        "SCORPION ALL TERRAIN PLUS": "Scorpion All Terrain Plus",
        "SCORPION ICE ZERO 2": "Scorpion Ice Zero 2",
        "SCORPION VERDE ALL SEASON": "Scorpion Verde All-Season",
        "SCORPION VERDE ALL-SEASON": "Scorpion Verde All-Season",
        "SCORPION VERDE": "Scorpion Verde",
        "SCORPION ZERO ALL SEASON": "Scorpion Zero All-Season",
        "SCORPION WINTER RUN FLAT": "Scorpion Winter Run Flat",
        "SCORPION WINTER": "Scorpion Winter",
        "SCORPION": "Scorpion",
        "ICE ZERO 2": "Ice Zero 2",
        "ICE ZERO FR": "Ice Zero Friction",
        "ICE ZERO": "Ice Zero",
        "WINTER CARVING": "Winter Carving",
        "WINTER ICE ZERO": "Winter Ice Zero",
        "WINTER SOTTOZERO SERIE 3 RUN FLAT": "Winter Sottozero Serie 3 Run Flat",
        "WINTER SOTTOZERO SERIE 3": "Winter Sottozero Serie 3",
    },
    "Powertrac": {
        "ADAMAS H/P": "Adamas H/P",
        "CITYRACING": "CityRacing",
        "CITYROVER": "CityRover",
        "CITYMARCH": "CityMarch",
        "ECOSPORT X77": "EcoSport X77",
        "ICE XPRO": "Ice Xpro",
        "LOADKING": "LoadKing",
        "POWER LANDER A/T": "Power Lander A/T",
        "POWER ROVER M/T": "Power Rover M/T",
        "RACING PRO": "Racing Pro",
        "SNOWPRO STUD 01": "SnowPro Stud 01",
        "SNOWPRO STUD 02": "SnowPro Stud 02",
        "SNOWPRO STUD": "SnowPro Stud",
        "SNOWVAN PRO": "SnowVan Pro",
        "VANTOUR": "VanTour",
        "WILDRANGER AT": "WildRanger A/T",
        "WILDRANGER A/T": "WildRanger A/T",
        "WILDRANGER MT": "WildRanger M/T",
        "WILDRANGER M/T": "WildRanger M/T",
    },
    "Roadcruza": {
        "RA1100": "RA1100",
        "RA3200": "RA3200",
    },
    "Roadmarch": {
        "SNOWROVER 868": "SnowRover 868",
        "SNOW ROVER 868": "SnowRover 868",
    },
    "Rotalla": {
        "S500": "S500",
    },
    "Royal Black": {
        "GAZILL": "Gazill",
        "ROYAL A/T": "Royal A/T",
        "ROYAL M/T": "Royal M/T",
        "ROYALCOMMERCIAL": "Royal Commercial",
        "ROYAL COMMERCIAL": "Royal Commercial",
        "ROYALCOMFORT": "Royal Comfort",
        "ROYAL COMFORT": "Royal Comfort",
        "ROYALECO": "Royal Eco",
        "ROYAL ECO": "Royal Eco",
        "ROYALEXPLORER EV": "Royal Explorer EV",
        "ROYAL EXPLORER EV": "Royal Explorer EV",
        "ROYALEXPLORER II": "Royal Explorer II",
        "ROYAL EXPLORER II": "Royal Explorer II",
        "ROYALEXPLORER": "Royal Explorer",
        "ROYAL EXPLORER": "Royal Explorer",
        "ROYALICE": "Royal Ice",
        "ROYAL ICE": "Royal Ice",
        "ROYALMILE": "Royal Mile",
        "ROYAL MILE": "Royal Mile",
        "ROYALPERFORMANCE": "Royal Performance",
        "ROYAL PERFORMANCE": "Royal Performance",
        "ROYALSPORT": "Royal Sport",
        "ROYAL SPORT": "Royal Sport",
        "ROYALSTUD 2": "RoyalStud II",
        "ROYAL STUD 2": "RoyalStud II",
        "ROYALSTUD II": "RoyalStud II",
        "ROYALSTUD": "RoyalStud",
        "ROYAL STUD": "RoyalStud",
        "ROYALWINTER": "Royal Winter",
        "ROYAL WINTER": "Royal Winter",
        "SPIDER R/T": "Spider R/T",
    },
    "Sailun": {
        "ATREZZO ELITE 2": "Atrezzo Elite 2",
        "ATREZZO ELITE": "Atrezzo Elite",
        "ATREZZO ZSR": "Atrezzo ZSR",
        "COMMERCIO PRO": "Commercio PRO",
        "ICE BLAZER ARCTIC EVO": "Ice Blazer Arctic Evo",
        "ICE BLAZER ARCTIC RFT": "Ice Blazer Arctic RFT",
        "ICE BLAZER ARCTIC": "Ice Blazer Arctic",
        "WST2": "Ice Blazer WST2",
        "WST3": "Ice Blazer WST3",
        "TERRAMAX A/T": "Terramax A/T",
        "TERRAMAX M/T": "TerraMax M/T",
        "TERRAMAX CVR": "Terramax CVR",
        "SV57": "Turismo SV57",
    },
    "Sonix": {
        "ECOPRO 99": "EcoPro 99",
        "ECO PRO 99": "EcoPro 99",
        "L-ZEAL 56": "L-Zeal 56",
        "PRIMESTAR 66": "Primestar 66",
        "PRIME UHP 08": "Prime UHP 08",
        "SNOWROVER 868": "SnowRover 868",
        "SNOW ROVER 868": "SnowRover 868",
        "SNOWROVER 989": "SnowRover 989",
        "SNOW ROVER 989": "SnowRover 989",
        "WINTER X PRO STUDS 77": "WinterXPro Studs 77",
        "WINTER XPRO STUDS 77": "WinterXPro Studs 77",
        "WINTERXPRO STUDS 77": "WinterXPro Studs 77",
        "WINTER X PRO STUDS 888": "WinterXPro Studs 888",
        "WINTER XPRO STUDS 888": "WinterXPro Studs 888",
        "WINTERXPRO STUDS 888": "WinterXPro Studs 888",
        "WINTERXPRO 888": "WinterXPro Studs 888",
    },
    "Sumaxx": {
        "ALL-TERRAIN A/T": "All-Terrain A/T",
        "MAX DRIFTING X": "Max Drifting X",
        "MAX RACING 86S": "Max Racing 86S",
        "MAX RANGER R/T": "Max Ranger R/T",
        "MAX SPEED R1": "Max Speed R1",
    },
    "Tigar": {
        "CARGO SPEED WINTER ": "Cargo Speed Winter",
        "ICE": "Ice",
        "ROAD-TERRAIN": "Road-Terrain",
        "ROAD TERRAIN": "Road-Terrain",
        "TOURING": "Touring",
        "ULTRA HIGH PERFORMANCE": "Ultra High Performance",
        "WINTER": "Winter",
    },
    "Torero (Matador)": {
        "MP30 FR": "MP30 FR",
        "MP30": "MP30",
        "MP47": "MP47",
        "MPS330": "MPS330",
        "MPS500": "MPS500",
    },
    "Torero": {
        "MP30 FR": "MP30 FR",
        "MP30": "MP30",
        "MP47": "MP47",
        "MP72": "MP72",
        "MP82": "MP82",
        "MPS125": "MPS125",
        "MPS330": "MPS330",
        "MPS500": "MPS500",
    },
    "Toyo": {
        "ICE-FREEZER": "Ice-Freezer",
        "NANOENERGY 3": "NanoEnergy 3",
        "OBGIZ": "Obgiz",
        "OBGSI6 LS": "OBGSi6 LS",
        "OBGSI6": "OBGSi6",
        "OBG3S": "OBG3S",
        "OBSERVE GSI5": "Observe GSi5",
        "OBSERVE G3-ICE": "Observe G3-ICE",
        "OBSERVE VAN": "Observe Van",
        "OPEN COUNTRY M/T": "Open Country M/T",
        "PROXES CF2S": "Proxes CF2S",
        "PROXES C1S": "Proxes C1S",
        "PROXES SPORT": "Proxes Sport",
        "PROXES T1S": "Proxes T1S",
    },
    "Triangle": {
        "LL01": "LL01",
        "LS01": "LS01",
        "PL01": "PL01",
        "PL02": "PL02",
        "PS01": "PS01",
        "TA01": "TA01",
        "TC101": "TC101",
        "TE301": "TE301",
        "TH201": "TH201",
        "TE307": "TE307",
        "TH202": "TH202",
        "TI501": "TI501",
        "TRD99 (M+S)": "TRD99 (M+S)",
        "TRD99": "TRD99",
        "TR259": "TR259",
        "TR281": "TR281",
        "TR292": "TR292",
        "TR645": "TR645",
        "TR646": "TR646",
        "TR652": "TR652",
        "TR-668А 14PR LT": "TR-668A 14PR LT",
        "TR-668А": "TR-668A",
        "TR-668A": "TR-668A",
        "TR668 14PR": "TR668 14PR",
        "TR668": "TR668",
        "TR-690": "TR-690",
        "TR737": "TR737",
        "TR757": "TR757",
        "TR777": "TR777",
        "TR928": "TR928",
        "TR968": "TR968",
        "TR978": "TR978",
        "TV701": "TV701",
    },
    "Tunga": {
        "PW-5": "Nordway 2 PW-5",
        "NORDWAY 2": "Nordway 2 PW-5",
        "ZODIAK 2": "Zodiak 2",
        "ZODIAK-2": "Zodiak 2",
        "NORDWAY": "Nordway",
    },
    "Viatti": {
        "V-130": "Strada Asimmetrico V-130",
        "PS-7": "Zodiak 2 PS-7",
        "V-237": "Bosco A/T V-237",
        "V-238": "Bosco H/T V-238",
        "V-523": "Bosco Nordico V-523",
        "BOSCO NORDICO": "Bosco Nordico V-523",
        "V-526": "Bosco S/T V-526",
        "BOSCO S/T": "Bosco S/T V-526",
        "V-522": "Brina Nordico V-522",
        "V-521": "Brina V-521",
        "V-528": "Brina Nordico V-528",
        "Strada Asimmetrico": "Strada Asimmetrico V-130",
        "V-134": "Strada 2 V-134",
        "V-524": "Vettore Inverno V-524",
        "V-525": "Vettore Brina V-525",
    },
    "Voltyre": {
        "RF-309": "RF-309",
    },
    "Westlake": {
        "H188": "H188",
        "SA37": "SA37",
        "SA57": "SA57",
        "SC328": "SC328",
        "SL369": "SL369",
        "SU318": "SU318",
        "SW606": "SW606",
        "SW608": "SW608",
        "SW612": "SW612",
        "SW618": "SW618",
        "SW628": "SW628",
        "Z-007": "Z-007 ZuperAce",
        "Z-107": "Z-107 ZuperEco",
        "Z-203": "Z-203",
        "Z-506": "Z-506",
        "Z-507": "Z-507",
    },
    "Wideway": {
        "ALL-TERRAIN T/A AK3": "All-Terrain T/A AK3",
        "BAJA KING A/T": "Baja King A/T",
        "SOLARFLEXX": "SolarFlexx",
        "WEYONE AK3": "Weyone AK3",
        "WEYP6 MT": "WEYP6 M/T",
    },
    "Winrun": {
        "R330": "R330",
    },
    "Yokohama": {
        "A348R": "A348R",
        "V103B": "Advan Sport V103B",
        "V103S": "Advan Sport V103S",
        "V105D": "Advan Sport V105D",
        "V105E N0": "Advan Sport V105E N0",
        "V105E": "Advan Sport V105E",
        "V105S": "Advan Sport V105S",
        "V105T": "Advan Sport V105T",
        "V105W": "Advan Sport V105W",
        "V105": "Advan Sport V105",
        "V107C MO": "Advan Sport V107C MO",
        "V107A": "Advan Sport V107A",
        "V107C": "Advan Sport V107C",
        "V107D": "Advan Sport V107D",
        "V107E": "Advan Sport V107E",
        "V107": "Advan Sport V107",
        "V552": "Advan dB V552",
        "V553": "Advan dB V553",
        "V701": "Advan Fleva V701",
        "V802": "Advan S.T. V802",
        "S35A": "AVID GT S35A",
        "AE50": "BluEarth-A AE-50",
        "AE-50": "BluEarth-A AE-50",
        "AE51A": "BluEarth-GT AE51A",
        "AE-51A": "BluEarth-GT AE51A",
        "AE51E": "BluEarth-GT AE51E",
        "AE-51E": "BluEarth-GT AE51E",
        "AE51H": "BluEarth-GT AE51H",
        "AE-51H": "BluEarth-GT AE51H",
        "AE51": "BluEarth-GT AE51",
        "AE-51": "BluEarth-GT AE51",
        "AE61A": "BluEarth-XT AE61A",
        "AE-61A": "BluEarth-XT AE61A",
        "AE61": "BluEarth-XT AE61",
        "AE-61": "BluEarth-XT AE61",
        "E70BZ": "BluEarth E70BZ",
        "E-70BZ": "BluEarth E70BZ",
        "ES32A": "BluEarth-Es ES32A",
        "ES-32A": "BluEarth-Es ES32A",
        "ES32": "BluEarth-Es ES32",
        "ES-32": "BluEarth-Es ES32",
        "G015": "Geolandar A/T G015",
        "G-015": "Geolandar A/T G015",
        "G31A": "G31A",
        "G055E": "Geolandar G055E",
        "G056": "Geolandar H/T G056",
        "G-056": "Geolandar H/T G056",
        "G057B": "Geolandar X-CV G057B",
        "G-057B": "Geolandar X-CV G057B",
        "G057": "Geolandar X-CV G057",
        "G-057": "Geolandar X-CV G057",
        "G058": "Geolandar CV G058",
        "G-058": "Geolandar CV G058",
        "G073": "Geolandar I/T-S G073",
        "G-073": "Geolandar I/T-S G073",
        "G003": "G003",
        "G075": "iceGuard Studless G075",
        "G-075": "iceGuard Studless G075",
        "G-65": "G65",
        "G900A": "G900A",
        "G94CV": "G94CV",
        "G98C": "G98C",
        "IG50 +": "iceGuard Studless iG50+",
        "IG50+": "iceGuard Studless iG50+",
        "IG-50+": "iceGuard Studless iG50+",
        "IG60A": "iceGuard Studless iG60A",
        "IG-60A": "iceGuard Studless iG60A",
        "IG60": "iceGuard Studless iG60",
        "IG-60": "iceGuard Studless iG60",
        "IG55": "iceGuard Stud iG55",
        "IG-55": "iceGuard Stud iG55",
        "IG65": "iceGuard Stud iG65",
        "IG-65": "iceGuard Stud iG65",
        "IG70A": "iceGuard iG70A",
        "IG-70A": "iceGuard iG70A",
        "IG70": "iceGuard iG70",
        "IG-70": "iceGuard iG70",
        "PA02J": "Parada Spec-X PA02J",
        "PA-02J": "Parada Spec-X PA02J",
        "PA02": "Parada Spec-X PA02",
        "PA-02": "Parada Spec-X PA02",
        "RY55": "BluEarth-Van RY55",
        "RY61": "BluEarth-Van All Season RY61",
        "RY-61": "BluEarth-Van All Season RY61",
        "V905": "BluEarth*Winter V905",
        "V906": "BluEarth*Winter V906",
        "V35A": "V35A",
        "WY01": "W.drive WY01",
        "WY-01": "W.drive WY01",
        "Y785R": "Y785R",
    },
    "БелШина": {
        "БЕЛ-143": "Бел-143",
        "БЕЛ-147": "Бел-147",
        "БЕЛ-217": "Бел-217",
        "БЕЛ-253": "Бел-253",
        "БЕЛ-254": "Бел-254",
        "БЕЛ-261": "Бел-261",
        "БЕЛ-262": "Бел-262",
        "БЕЛ-264": "Бел-264",
        "БЕЛ-267": "Бел-267",
        "БЕЛ-274": "Бел-274",
        "БЕЛ-280": "Бел-280",
        "БЕЛ-281": "Бел-281",
        "БЕЛ-282": "Бел-282",
        "БЕЛ-283": "Бел-283",
        "БЕЛ-286": "Бел-286",
        "БЕЛ-287": "Бел-287",
        "БЕЛ-293": "Бел-293",
        "БЕЛ-294": "Бел-294",
        "БЕЛ-297": "Бел-297",
        "БЕЛ-303": "Бел-303",
        "БЕЛ-313": "Бел-313",
        "БЕЛ-317": "Бел-317",
        "БЕЛ-329": "Бел-329",
        "БЕЛ-337": "Бел-337",
        "БЕЛ-341": "Бел-341",
        "БЕЛ-347": "Бел-347",
        "БЕЛ-354": "Бел-354",
        "БЕЛ-357": "Бел-357",
        "БЕЛ-367": "Бел-367",
        "БЕЛ-377": "Бел-377",
        "БЕЛ-397": "Бел-397",
        "БЕЛ-402": "Бел-402",
        "БЕЛ-403": "Бел-403",
        "БЕЛ-409": "Бел-409",
        "БЕЛ-494": "Бел-494",
        "БЕЛ-509": "Бел-509",
        "БЕЛ-517": "Бел-517",
        "БИ-522": "БИ-522",
    },
    "ВолШЗ": {
        "VOLTYRE RF-309": "Voltyre RF-309",
        "ВС-22": "ВС-22",
        "ВЛИ-5": "ВЛИ-5",
        "ВЛ-54": "ВЛ-54",
        "С-156": "С-156",
    },
}

SPOKES: set[str] = {" Ш", "ШИПЫ", "ШИП"}
XL: set[str] = {" XL"}
